package installsh

// Regression guards for issue #58: the remote runners generated by
// INSTALL_GSD_TEST.sh must isolate each project's rsync mirror tree, and the
// build step must invoke a build script that exists (the retired build:sdk was
// a silent no-op).

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func readInstallScript(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "INSTALL_GSD_TEST.sh"))
	if err != nil {
		t.Fatalf("read INSTALL_GSD_TEST.sh: %v", err)
	}
	return string(data)
}

// mirrorDirAssign matches the MIRROR_DIR assignment lines in both runner bodies.
var mirrorDirAssign = regexp.MustCompile(`(?m)^MIRROR_DIR=.*$`)

// mirrorAssigns returns the (identical) per-body MIRROR_DIR derivation lines.
func mirrorAssigns(t *testing.T, script string) []string {
	t.Helper()
	assigns := mirrorDirAssign.FindAllString(script, -1)
	if len(assigns) != 2 {
		t.Fatalf("expected MIRROR_DIR assigned in both runner bodies (Linux + Windows), found %d: %v", len(assigns), assigns)
	}
	return assigns
}

// evalMirror evaluates the shipped MIRROR_DIR derivation line for a given
// PROJECT_DIR, with an optional shell prelude (used to force the hash-tool
// fallback). It runs under the same `set -euo pipefail` the runner uses.
func evalMirror(t *testing.T, line, projectDir, prelude string) string {
	t.Helper()
	script := `set -euo pipefail; ` + prelude + `PROJECT_DIR="$1"; ` + line + `; printf '%s' "$MIRROR_DIR"`
	out, err := exec.Command("bash", "-c", script, "bash", projectDir).CombinedOutput()
	if err != nil {
		t.Fatalf("eval MIRROR_DIR derivation for %q (prelude %q): %v\n%s", projectDir, prelude, err, out)
	}
	return string(out)
}

func TestInstallScript_MirrorDirIsPerProject(t *testing.T) {
	script := readInstallScript(t)

	// The fixed host-wide constant was the root cause — it must be gone.
	if strings.Contains(script, "gsd-mirror-get-shit-done") {
		t.Error("INSTALL_GSD_TEST.sh still hard-codes the shared MIRROR_DIR " +
			`"gsd-mirror-get-shit-done" — concurrent runs would collide (issue #58)`)
	}

	assigns := mirrorAssigns(t, script)
	for _, a := range assigns {
		if !strings.Contains(a, "$PROJECT_DIR") {
			t.Errorf("MIRROR_DIR assignment does not derive from $PROJECT_DIR: %q", a)
		}
	}
	if assigns[0] != assigns[1] {
		t.Errorf("Linux and Windows bodies derive MIRROR_DIR differently:\n  %q\n  %q", assigns[0], assigns[1])
	}

	// Evaluate the actual shipped derivation: distinct project dirs must map to
	// distinct mirrors, and the mapping must be deterministic.
	a := evalMirror(t, assigns[0], "/Users/alice/proj", "")
	b := evalMirror(t, assigns[0], "/Users/alice/proj-worktree-2", "")
	aAgain := evalMirror(t, assigns[0], "/Users/alice/proj", "")

	if a == b {
		t.Errorf("distinct project dirs produced the same mirror %q — no isolation", a)
	}
	if a != aAgain {
		t.Errorf("derivation not deterministic: %q vs %q", a, aAgain)
	}
	if !regexp.MustCompile(`^gsd-mirror-[0-9a-f]{12}$`).MatchString(a) {
		t.Errorf("mirror name %q does not match gsd-mirror-<hash12>", a)
	}
}

// TestInstallScript_MirrorDirDerivedAfterProjectDir guards the ordering: the
// derivation must come AFTER PROJECT_DIR is computed in each body. If it were
// moved back above PROJECT_DIR it would hash an empty string — one constant
// mirror for every project — silently re-introducing #58 while still textually
// "deriving from $PROJECT_DIR".
func TestInstallScript_MirrorDirDerivedAfterProjectDir(t *testing.T) {
	script := readInstallScript(t)
	projectIdx := indicesOf(script, "\nPROJECT_DIR=\"$(git rev-parse")
	mirrorIdx := indicesOf(script, "\nMIRROR_DIR=\"gsd-mirror-$(")

	if len(mirrorIdx) != 2 {
		t.Fatalf("expected 2 derived MIRROR_DIR assignments, got %d", len(mirrorIdx))
	}
	if len(projectIdx) < 2 {
		t.Fatalf("expected PROJECT_DIR assigned in each remote runner body, got %d", len(projectIdx))
	}

	// Each derived MIRROR_DIR must be preceded by a distinct PROJECT_DIR (its own
	// body's), proving per-body ordering.
	used := map[int]bool{}
	for _, m := range mirrorIdx {
		nearest := -1
		for _, p := range projectIdx {
			if p < m && p > nearest {
				nearest = p
			}
		}
		if nearest == -1 {
			t.Errorf("MIRROR_DIR derivation at offset %d has no preceding PROJECT_DIR (would hash empty)", m)
			continue
		}
		if used[nearest] {
			t.Errorf("two MIRROR_DIR derivations share the same preceding PROJECT_DIR at %d — ordering looks wrong", nearest)
		}
		used[nearest] = true
	}
}

// TestInstallScript_HashFallbackMatchesPrimary exercises the
// `shasum -a 256 || sha256sum` fallback: when shasum is unavailable, the
// sha256sum branch must produce the identical SHA-256-based mirror name (so the
// fix works on Linux dev workstations that ship sha256sum, not shasum).
func TestInstallScript_HashFallbackMatchesPrimary(t *testing.T) {
	if _, err := exec.LookPath("shasum"); err != nil {
		t.Skip("shasum not available; primary path absent on this host")
	}
	if _, err := exec.LookPath("sha256sum"); err != nil {
		t.Skip("sha256sum not available; cannot exercise the fallback path")
	}
	line := mirrorAssigns(t, readInstallScript(t))[0]

	primary := evalMirror(t, line, "/Users/alice/proj", "")
	// Shadow shasum with a function that fails so the `|| sha256sum` leg runs.
	fallback := evalMirror(t, line, "/Users/alice/proj", "shasum() { return 127; }; ")

	if primary != fallback {
		t.Errorf("fallback (sha256sum) mirror %q != primary (shasum) mirror %q", fallback, primary)
	}
}

func TestInstallScript_NoRetiredBuildSdk(t *testing.T) {
	script := readInstallScript(t)
	if strings.Contains(script, "build:sdk") {
		t.Error("INSTALL_GSD_TEST.sh still references the retired build:sdk script (silent no-op) — use `npm run build --if-present` (issue #58)")
	}
	if !strings.Contains(script, "npm run build --if-present") {
		t.Error("expected the runner build step to invoke `npm run build --if-present`")
	}
}

// indicesOf returns the byte offsets of every occurrence of sub in s.
func indicesOf(s, sub string) []int {
	var out []int
	for off := 0; ; {
		i := strings.Index(s[off:], sub)
		if i < 0 {
			break
		}
		out = append(out, off+i)
		off += i + len(sub)
	}
	return out
}
